import { createStitches } from "@stitches/react";
// import { GeistSans } from "geist/font/sans";
export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      background: "0 0% 100%",
      foreground: "222.2 84% 4.9%",
      card: "0 0% 100%",
      "card-foreground": "222.2 84% 4.9%",
      popover: "0 0% 100%",
      "popover-foreground": "222.2 84% 4.9%",
      primary: "221.2 83.2% 53.3%",
      "primary-foreground": "210 40% 98%",
      secondary: "210 40% 96.1%",
      "secondary-foreground": "222.2 47.4% 11.2%",
      muted: "210 40% 96.1%",
      "muted-foreground": "215.4 16.3% 46.9%",
      accent: "210 40% 96.1%",
      "accent-foreground": "222.2 47.4% 11.2%",
      destructive: "0 84.2% 60.2%",
      "destructive-foreground": "210 40% 98%",
      border: "214.3 31.8% 91.4%",
      input: "214.3 31.8% 91.4%",
      ring: "221.2 83.2% 53.3%",
      radius: "0.5rem",
    },
  },
});
export const reset = globalCss({
  "*,\n::before,\n::after": {
    boxSizing: "border-box",
    borderWidth: "0",
    borderStyle: "solid",
    borderColor: "#e5e7eb",
  },
  "::before,\n::after": { "--tw-content": "''" },
  "html,\n:host": {
    lineHeight: 1.5,
    WebkitTextSizeAdjust: "100%",
    MozTabSize: "4",
    tabSize: 4,
    fontFamily:
      'GeistSans , ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontFeatureSettings: "normal",
    fontVariationSettings: "normal",
    WebkitTapHighlightColor: "transparent",
  },
  body: { margin: "0", lineHeight: "inherit" },
  hr: { height: "0", color: "inherit", borderTopWidth: "1px" },
  "abbr:where([title])": { textDecoration: "underline dotted" },
  "h1,\nh2,\nh3,\nh4,\nh5,\nh6": { fontSize: "inherit", fontWeight: "inherit" },
  a: { color: "inherit", textDecoration: "inherit" },
  "b,\nstrong": { fontWeight: "bolder" },
  "code,\nkbd,\nsamp,\npre": {
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontFeatureSettings: "normal",
    fontVariationSettings: "normal",
    fontSize: "1em",
  },
  small: { fontSize: "80%" },
  "sub,\nsup": {
    fontSize: "75%",
    lineHeight: 0,
    position: "relative",
    verticalAlign: "baseline",
  },
  sub: { bottom: "-0.25em" },
  sup: { top: "-0.5em" },
  table: {
    textIndent: "0",
    borderColor: "inherit",
    borderCollapse: "collapse",
  },
  "button,\ninput,\noptgroup,\nselect,\ntextarea": {
    fontFamily: "inherit",
    fontFeatureSettings: "inherit",
    fontVariationSettings: "inherit",
    fontSize: "100%",
    fontWeight: "inherit",
    lineHeight: "inherit",
    color: "inherit",
    margin: "0",
    padding: "0",
  },
  "button,\nselect": { textTransform: "none" },
  "button,\n[type='button'],\n[type='reset'],\n[type='submit']": {
    WebkitAppearance: "button",
    backgroundColor: "transparent",
    backgroundImage: "none",
  },
  ":-moz-focusring": { outline: "auto" },
  ":-moz-ui-invalid": { boxShadow: "none" },
  progress: { verticalAlign: "baseline" },
  "::-webkit-inner-spin-button,\n::-webkit-outer-spin-button": {
    height: "auto",
  },
  "[type='search']": { WebkitAppearance: "textfield", outlineOffset: "-2px" },
  "::-webkit-search-decoration": { WebkitAppearance: "none" },
  "::-webkit-file-upload-button": {
    WebkitAppearance: "button",
    font: "inherit",
  },
  summary: { display: "list-item" },
  "blockquote,\ndl,\ndd,\nh1,\nh2,\nh3,\nh4,\nh5,\nh6,\nhr,\nfigure,\np,\npre":
    {
      margin: "0",
    },
  fieldset: { margin: "0", padding: "0" },
  legend: { padding: "0" },
  "ol,\nul,\nmenu": { listStyle: "none", margin: "0", padding: "0" },
  dialog: { padding: "0" },
  textarea: { resize: "vertical" },
  "input::placeholder,\ntextarea::placeholder": {
    opacity: 1,
    color: "#9ca3af",
  },
  'button,\n[role="button"]': { cursor: "pointer" },
  ":disabled": { cursor: "default" },
  "img,\nsvg,\nvideo,\ncanvas,\naudio,\niframe,\nembed,\nobject": {
    display: "block",
    verticalAlign: "middle",
  },
  "img,\nvideo": { maxWidth: "100%", height: "auto" },
  "[hidden]": { display: "none" },
  "*, ::before, ::after": {
    "--tw-border-spacing-x": "0",
    "--tw-border-spacing-y": "0",
    "--tw-translate-x": "0",
    "--tw-translate-y": "0",
    "--tw-rotate": "0",
    "--tw-skew-x": "0",
    "--tw-skew-y": "0",
    "--tw-scale-x": "1",
    "--tw-scale-y": "1",
    "--tw-pan-x": "  ",
    "--tw-pan-y": "  ",
    "--tw-pinch-zoom": "  ",
    "--tw-scroll-snap-strictness": "proximity",
    "--tw-gradient-from-position": "  ",
    "--tw-gradient-via-position": "  ",
    "--tw-gradient-to-position": "  ",
    "--tw-ordinal": "  ",
    "--tw-slashed-zero": "  ",
    "--tw-numeric-figure": "  ",
    "--tw-numeric-spacing": "  ",
    "--tw-numeric-fraction": "  ",
    "--tw-ring-inset": "  ",
    "--tw-ring-offset-width": "0px",
    "--tw-ring-offset-color": "#fff",
    "--tw-ring-color": "rgb(59 130 246 / 0.5)",
    "--tw-ring-offset-shadow": "0 0 #0000",
    "--tw-ring-shadow": "0 0 #0000",
    "--tw-shadow": "0 0 #0000",
    "--tw-shadow-colored": "0 0 #0000",
    "--tw-blur": "  ",
    "--tw-brightness": "  ",
    "--tw-contrast": "  ",
    "--tw-grayscale": "  ",
    "--tw-hue-rotate": "  ",
    "--tw-invert": "  ",
    "--tw-saturate": "  ",
    "--tw-sepia": "  ",
    "--tw-drop-shadow": "  ",
    "--tw-backdrop-blur": "  ",
    "--tw-backdrop-brightness": "  ",
    "--tw-backdrop-contrast": "  ",
    "--tw-backdrop-grayscale": "  ",
    "--tw-backdrop-hue-rotate": "  ",
    "--tw-backdrop-invert": "  ",
    "--tw-backdrop-opacity": "  ",
    "--tw-backdrop-saturate": "  ",
    "--tw-backdrop-sepia": "",
  },
  "::backdrop": {
    "--tw-border-spacing-x": "0",
    "--tw-border-spacing-y": "0",
    "--tw-translate-x": "0",
    "--tw-translate-y": "0",
    "--tw-rotate": "0",
    "--tw-skew-x": "0",
    "--tw-skew-y": "0",
    "--tw-scale-x": "1",
    "--tw-scale-y": "1",
    "--tw-pan-x": "  ",
    "--tw-pan-y": "  ",
    "--tw-pinch-zoom": "  ",
    "--tw-scroll-snap-strictness": "proximity",
    "--tw-gradient-from-position": "  ",
    "--tw-gradient-via-position": "  ",
    "--tw-gradient-to-position": "  ",
    "--tw-ordinal": "  ",
    "--tw-slashed-zero": "  ",
    "--tw-numeric-figure": "  ",
    "--tw-numeric-spacing": "  ",
    "--tw-numeric-fraction": "  ",
    "--tw-ring-inset": "  ",
    "--tw-ring-offset-width": "0px",
    "--tw-ring-offset-color": "#fff",
    "--tw-ring-color": "rgb(59 130 246 / 0.5)",
    "--tw-ring-offset-shadow": "0 0 #0000",
    "--tw-ring-shadow": "0 0 #0000",
    "--tw-shadow": "0 0 #0000",
    "--tw-shadow-colored": "0 0 #0000",
    "--tw-blur": "  ",
    "--tw-brightness": "  ",
    "--tw-contrast": "  ",
    "--tw-grayscale": "  ",
    "--tw-hue-rotate": "  ",
    "--tw-invert": "  ",
    "--tw-saturate": "  ",
    "--tw-sepia": "  ",
    "--tw-drop-shadow": "  ",
    "--tw-backdrop-blur": "  ",
    "--tw-backdrop-brightness": "  ",
    "--tw-backdrop-contrast": "  ",
    "--tw-backdrop-grayscale": "  ",
    "--tw-backdrop-hue-rotate": "  ",
    "--tw-backdrop-invert": "  ",
    "--tw-backdrop-opacity": "  ",
    "--tw-backdrop-saturate": "  ",
    "--tw-backdrop-sepia": "",
  },
});
reset();
